CHANNELS:
  channels_delay: 30
  stagger_start_seconds: 5
  defaults:
    scan_interval: 420
    history_limit: 50
    history_days: 2
    overlap: 5
    forward_to: []
    keywords: []
  channels: {}
