# Ключевые слова для поиска mko_nikolay
#      'жилье':{'ищем','ищу','сниму','снять', 'сдает', 'сдать'},
#      'квартир':{'ищем','ищу','сниму','снять', 'сдает', 'сдать'}
{
  CHANNELS: {
    'channels_delay': 30,
    channels: {
      'DEFAULTS':
        { 'scan_interval': 420,
          'stagger_start_seconds': 5,
          'history_limit': 50,
          'history_days': 2,
          'overlap': 5,
          'forward_to': [ 'namanelly' ],
          'keywords': [
            '(tivat | тиват) -услуг* -трансфер* -массаж -ремонт -iphone -сдаю -сдам -аренд*  -мясо -сыр -заказ*',
            '(budv* | будв* | херцег* | котор | бечичи) телефон -iphone -услуг* -ремонт',
            '(budv* | будв* | херцег* | котор | бечичи) наушники -iphone -беспроводные',
            '(budv* | будв* | херцег* | котор | бечичи) (кроссовки | обувь) (39 |40 | 43 | 44 )',
            '(budv* | будв* | херцег* | котор | бечичи) (инструмент | перфоратор | дрель | ушм | болгарка | *лобзик | электролобзик)',
            '(budv* | будв* | херцег* | котор | бечичи) пылесос (робот | строительный)',
            '(budv* | будв* | херцег* | котор | бечичи) (notebook | ноут* | *book) -услуг* -ремонт* -mac*',
            '(budv* | будв* | херцег* | котор | бечичи) стеллаж*',
            '(budv* | будв* | херцег* | котор | бечичи) ящик*',
          ],
        },
      'channel_1': {
      },
      'channel_2': {
      },
      'channel_3': {
      }

    },
  },
}